services:
    app:
        build: .
        ports:
            - "8080:8080"
        depends_on:
            - redis
            - postgres
        environment:
            - DB_USER=postgres
            - DB_PASSWORD=1234
            - DB_HOST=postgres
            - DB_PORT=5432
            - DB_NAME=mydb
            - REDIS_HOST=redis
            - REDIS_PORT=6379
    adminer:
        image: adminer
        ports:
            - "8081:8080"
    redis:
        image: redis:latest

    postgres:
        image: postgres:latest
        ports:
            - "5431:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=1234
            - POSTGRES_DB=mydb
        volumes:
            - postgres-data:/var/lib/postgresql/data

volumes:
    postgres-data: